### ISSUE TITLE
Punishments and Rewards: more action

### ISSUE THREAD

**Issue by es707** [e102/Punishment-Experiment#72]
I want computers to be punishing more and using a bigger range of rewards and punishments.
Only one computer should be not prone to reward, but all of them should punish.
They should spend much more money when the gap is bigger. basically I want them to be punishing and rewarding a lot.

**Comment by e102** [comment]
I'm not sure exactly what you want. Go into calculate_AI_contribution and make the changes you want. The format is AI contribution = player_contribution + a random number from x to y
